### ISSUE TITLE
Add crop feature to image (engagement & Who is Listening)

### ISSUE THREAD

**Issue by marieanik** [bcgov/met-public#1125]
As Jad discovered in #955, we can implement this feature on the engagement page and Who is Listening widget.

https://timetoprogram.com/crop-image-reactjs/

We should also change the text to mention which file types are accepted (.jpg, .png, .gif, .tiff, .pdf?)

Engagement:
"Drag and drop some files here, or click to select files.
Accepted formats are ...
Image must be at least ... px x ... px"

Widget:
"Drag and drop some files here, or click to select files.
Accepted formats are ..."

Centre-aligned for both, widget font-size: 13px

![Screenshot 2023-01-18 at 1.58.34 PM.png](https://images.zenhubusercontent.com/6261bc1a04c6a94c2edadddd/39029e93-308d-4e4c-9482-9fc8aabe9700)

**Comment by tiagograf-AOT** [comment]
TBD Aspect Ratio for Banner and Avatar

**Comment by tiagograf-AOT** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MET-Ops-6254279dcfa60b0010ea5a0d/issues/bcgov/met-public/1125?planning-poker) with Zenhub @djnunez-aot @jadmsaadaot @saravanpa-aot @VineetBala-AOT

**Comment by jadmsaadaot** [comment]
Upon discussion with @marieanik, the following points were concluded:

- Make objectFit 'cover'
- Have an unchangeable consistent aspect ratio of 1920 / 700
- remove ratio options
- could live without, check if we can make the ROI of the image on the right side rather than on the middle when image is resized
