### ISSUE TITLE
Add Admin to a specific Tenant

### ISSUE THREAD

**Issue by tiagograf-AOT** [bcgov/met-public#1439]
As a MET Admin I want to be able to assign a Tenant "Instance Admin"  so that it can manage the tenant instance.

> Add Instance Admin via keycloak 
> Create a new Tenant Ministry in the database (potentially postman script)

**Comment by carlygreenehill** [comment]
@saravanpa-aot  @marieanik @sidtobias    Is this something we need to complete before end of project? I would argue it's not directly outlined in the charter, but wondering if you feel strongly about finishing it... or documenting it and including it Parking Lot.

**Comment by sidtobias** [comment]
@carlygreenehill methinks this is included in the roles you may have sorted but may have different names.  Super Admin being Steve and Tenant Admin being a Ministry Super User

**Comment by carlygreenehill** [comment]
@sidtobias not quite. In our original designs, there was the following hierarchy: 

- MET Admin - example, Steve
- Instance Admin - example, Carly or Geoff for EAO
- Super User - example, Josh
- Team Members - example, Brennan Hutchinson
- Viewer - example, Julie Chace

We haven't made any screens custom to the MET Admin or Instance Admin. But that's why I want to check in with @saravanpa-aot because as long as Steve has a way to appoint a Tenant Admin on the back end, we should be good.

**Comment by saravanpa-aot** [comment]
> @sidtobias not quite. In our original designs, there was the following hierarchy:
> 
> * MET Admin - example, Steve
> * Instance Admin - example, Carly or Geoff for EAO
> * Superuser - example, Josh
> * Team Members - example, Brennan Hutchinson
> * Viewer - example, Julie Chace
> * Reviewer - someone invited to review a specific engagement/survey
> 
> We haven't made any screens custom to the MET Admin or Instance Admin. But that's why I want to check in with @saravanpa-aot because as long as Steve has a way to appoint a Tenant Admin on the back end, we should be good.

we can support MET Admin in the backend..We need to pull this story in the sprint

**Comment by VineetBala-AOT** [comment]
New group INSTANCE_ADMIN has been created in keycloak with role create_tenant.
