### ISSUE TITLE
Reassign role: Viewer/Reviewer/TM/Superuser

### ISSUE THREAD

**Issue by marieanik** [bcgov/met-public#1907]
As a Superuser, I want to be able to assign a different role to an existing user from the user management screen so that I can keep my users up-to-date in the system.

*Superuser toggle removed from User Details screen
*Engagement UM tab will remain to be only for TM
*Table should record role for TM/Reviewer (so that when a Reviewer becomes a TM, we know what engagement they were assigned to in a specific role)

**Comment by TayaLee8** [comment]
From **User Management** tab on side navigation:
![image.png](https://images.zenhubusercontent.com/63c8350e7cda3e3cc2a4ce73/f6c68554-ec58-4966-92d6-2894f6b7a7c4)
We will use **Jane Doe** for our scenario. (Team Member -> Superuser)

When Action drop down is clicked, you get two options: **Assign to an Engagement** (already existing) and **Reassign Role.**
When Reassign Role is clicked, you get Reassign Role pop-up:
![image.png](https://images.zenhubusercontent.com/63c8350e7cda3e3cc2a4ce73/dc4d1983-c0a3-4df5-bcfc-806bc41c5b87) 
All Role options will display except for their current role (if possible by devs). Jane Doe is assigned as a Superuser.

On User Details page, their Current Role will display at the top. The table will show the users history such as current/previous engagements, their role on each engagement, the date added to the engagement, their status on the engagement, and date revoked from the engagement (if applicable). 
![image.png](https://images.zenhubusercontent.com/63c8350e7cda3e3cc2a4ce73/37dea363-5bdd-4f2a-a55f-9aa2865184ab)

If a user is reassigned a role, they must be revoked from all engagements as their current role and reassigned as their new role. This is only not applicable for Superusers, as Superusers are not assigned engagements (they have access to everything). In this scenario, Jane Doe does not have any "Active" engagements because she is a Superuser. She was not revoked from her engagements as a Team Member because as a Superuser she still has access to them. 

See full flow and rules here:
![image.png](https://images.zenhubusercontent.com/63c8350e7cda3e3cc2a4ce73/95fa6fa0-2ccc-4d4c-8f14-f15d9077de0d)

**Comment by jadmsaadaot** [comment]
Reading this task I misunderstood the part "and must be readded as a TM" to mean this should happen programmatically as the user is reassigned their new role. But after a further discussion this was pointed out to me that this is meant to happen manually. Meaning, the user is revoked from all their engagements and the process of reassignment them to engagements happens manually after the reassign user role event is done.

As a consequence of the misunderstanding a logic was added in the code to programmatically reassign users to their revoked memberships with the new role, which was later removed in a following PR. As thing stand, a user is revoked from their engagements after their role is reassigned.

**Comment by TayaLee8** [comment]
Closing this and creating related bugs:
#2144
#2145
